"""Emit paper/generated/macros.tex from archived benchmark output files.

Sources:
  benchmarks/results/gate_false_positives.txt
  benchmarks/results/gate_sa_convergence.txt
  benchmarks/results/gate_retrieval_precision.txt
  benchmarks/results_seeds1-5/summary_table.md

Output:
  paper/generated/macros.tex

Run from the repo root:
  uv run python paper/scripts/build_macros.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
GATE_DIR = REPO / "benchmarks" / "results"
E2E_SUMMARY = REPO / "benchmarks" / "results_seeds1-5" / "summary_table.md"
OUT = REPO / "paper" / "generated" / "macros.tex"


def _read(path: Path) -> str:
    if not path.exists():
        raise FileNotFoundError(f"missing input: {path}")
    return path.read_text()


def parse_false_positives(text: str) -> dict[str, str]:
    m_unc = re.search(r"Without correction:\s+([\d.]+)", text)
    m_corr = re.search(r"With Holm-Bonferroni:\s+([\d.]+)", text)
    m_red = re.search(r"Reduction:\s+(\d+)%", text)
    if not (m_unc and m_corr and m_red):
        raise ValueError("could not parse gate_false_positives.txt")
    return {
        "fpUncorrected": m_unc.group(1),
        "fpCorrected": m_corr.group(1),
        "fpReductionPct": m_red.group(1),
    }


def parse_sa(text: str) -> dict[str, str]:
    m_fixed = re.search(r"Fixed SA best score \(avg\):\s+([\d.]+)", text)
    m_adapt = re.search(r"Adaptive SA best score \(avg\):\s+([\d.]+)", text)
    m_imp = re.search(r"Improvement:\s+([\d.]+)%", text)
    m_wins = re.search(r"Adaptive wins:\s+(\d+)/(\d+)", text)
    if not (m_fixed and m_adapt and m_imp and m_wins):
        raise ValueError("could not parse gate_sa_convergence.txt")
    return {
        "saFixedAvg": m_fixed.group(1),
        "saAdaptiveAvg": m_adapt.group(1),
        "saImprovementPct": m_imp.group(1),
        "saAdaptiveWins": m_wins.group(1),
        "saTotalSeeds": m_wins.group(2),
    }


def parse_retrieval(text: str) -> dict[str, str]:
    m_jac = re.search(r"Jaccard precision@5:\s+([\d.]+)", text)
    m_tfidf = re.search(r"TF-IDF\s+precision@5:\s+([\d.]+)", text)
    m_ratio = re.search(r"Ratio.*:\s+([\d.]+)x", text)
    if not (m_jac and m_tfidf and m_ratio):
        raise ValueError("could not parse gate_retrieval_precision.txt")
    return {
        "retrievalJaccard": m_jac.group(1),
        "retrievalTFIDF": m_tfidf.group(1),
        "retrievalRatio": m_ratio.group(1),
    }


_E2E_ROW = re.compile(
    r"\|\s*(B[1-5])\s*\|\s*([a-z]+)\s+vs\s+([a-z]+)\s*\|\s*"
    r"([\d.]+)\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|"
)


def parse_e2e(text: str) -> dict[str, str]:
    means: dict[tuple[str, str], float] = {}
    for line in text.splitlines():
        m = _E2E_ROW.search(line)
        if not m:
            continue
        target = m.group(1)
        a = m.group(2)
        b = m.group(3)
        means[(target, a)] = float(m.group(4))
        means[(target, b)] = float(m.group(5))

    # TeX control sequences cannot contain digits; spell B1..B5 as Bone..Bfive.
    word = {"B1": "Bone", "B2": "Btwo", "B3": "Bthree", "B4": "Bfour", "B5": "Bfive"}

    out: dict[str, str] = {}
    for target in ("B1", "B2", "B3", "B4", "B5"):
        for cfg in ("raw", "greedy", "control", "treatment"):
            key = (target, cfg)
            if key in means:
                out[f"mean{word[target]}{cfg.capitalize()}"] = f"{means[key]:.4f}"

    def pct(a: float, b: float, minimize: bool = False) -> str:
        if a == 0:
            return "0.0"
        delta = (b - a) / a * 100.0
        if minimize:
            delta = -delta
        sign = "+" if delta >= 0 else ""
        return f"{sign}{delta:.1f}"

    deltas: dict[str, tuple[str, str, bool]] = {
        f"deltaTC{word['B1']}": ("B1", "control", False),
        f"deltaTC{word['B2']}": ("B2", "control", False),
        f"deltaTC{word['B3']}": ("B3", "control", True),
        f"deltaTC{word['B4']}": ("B4", "control", False),
        f"deltaTC{word['B5']}": ("B5", "control", False),
    }
    for macro, (tgt, base_cfg, minimize) in deltas.items():
        a = means.get((tgt, base_cfg))
        b = means.get((tgt, "treatment"))
        if a is not None and b is not None:
            out[macro] = pct(a, b, minimize=minimize)

    # Arithmetic (un-normalized) delta for B3 prose, where the surface
    # convention reports the raw signed change because B3 minimizes.
    a = means.get(("B3", "control"))
    b = means.get(("B3", "treatment"))
    if a is not None and b is not None:
        out["deltaTCBthreeArith"] = pct(a, b, minimize=False)
    return out


def render(macros: dict[str, str]) -> str:
    lines = [
        "% paper/generated/macros.tex",
        "% AUTO-GENERATED by paper/scripts/build_macros.py — do not edit by hand.",
        "% Source files:",
        "%   benchmarks/results/gate_false_positives.txt",
        "%   benchmarks/results/gate_sa_convergence.txt",
        "%   benchmarks/results/gate_retrieval_precision.txt",
        "%   benchmarks/results_seeds1-5/summary_table.md",
        "",
    ]
    for name, value in macros.items():
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    macros: dict[str, str] = {}
    macros.update(parse_false_positives(_read(GATE_DIR / "gate_false_positives.txt")))
    macros.update(parse_sa(_read(GATE_DIR / "gate_sa_convergence.txt")))
    macros.update(parse_retrieval(_read(GATE_DIR / "gate_retrieval_precision.txt")))
    macros.update(parse_e2e(_read(E2E_SUMMARY)))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(macros))
    print(f"wrote {len(macros)} macros to {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
